-- ============================================================
-- NYC YELLOW TAXI DATA WAREHOUSE
-- ============================================================

CREATE SCHEMA IF NOT EXISTS warehouse;


-- ============================================================
-- DROP OLD WAREHOUSE TABLES
-- This makes the script safe to rerun.
-- We are NOT touching staging.
-- ============================================================

DROP TABLE IF EXISTS warehouse.fact_trips CASCADE;
DROP TABLE IF EXISTS warehouse.dim_date CASCADE;
DROP TABLE IF EXISTS warehouse.dim_zone CASCADE;
DROP TABLE IF EXISTS warehouse.dim_vendor CASCADE;
DROP TABLE IF EXISTS warehouse.dim_payment_type CASCADE;
DROP TABLE IF EXISTS warehouse.dim_rate_code CASCADE;


-- ============================================================
-- 1. DATE DIMENSION
-- ============================================================

CREATE TABLE warehouse.dim_date (
    date_key INTEGER PRIMARY KEY,
    full_date DATE UNIQUE,
    year SMALLINT,
    quarter SMALLINT,
    month SMALLINT,
    month_name VARCHAR(20),
    day SMALLINT,
    day_name VARCHAR(20),
    day_of_week SMALLINT,
    week_of_year SMALLINT,
    is_weekend BOOLEAN
);


-- Unknown date row
INSERT INTO warehouse.dim_date (
    date_key,
    full_date,
    year,
    quarter,
    month,
    month_name,
    day,
    day_name,
    day_of_week,
    week_of_year,
    is_weekend
)
VALUES (
    0,
    NULL,
    NULL,
    NULL,
    NULL,
    'Unknown',
    NULL,
    'Unknown',
    NULL,
    NULL,
    NULL
);


-- Generate dates from the actual trip data
INSERT INTO warehouse.dim_date (
    date_key,
    full_date,
    year,
    quarter,
    month,
    month_name,
    day,
    day_name,
    day_of_week,
    week_of_year,
    is_weekend
)
SELECT
    (
        EXTRACT(YEAR FROM d)::INTEGER * 10000
        +
        EXTRACT(MONTH FROM d)::INTEGER * 100
        +
        EXTRACT(DAY FROM d)::INTEGER
    ) AS date_key,

    d::DATE AS full_date,

    EXTRACT(YEAR FROM d)::SMALLINT,

    EXTRACT(QUARTER FROM d)::SMALLINT,

    EXTRACT(MONTH FROM d)::SMALLINT,

    TO_CHAR(d, 'Month'),

    EXTRACT(DAY FROM d)::SMALLINT,

    TO_CHAR(d, 'Day'),

    EXTRACT(ISODOW FROM d)::SMALLINT,

    EXTRACT(WEEK FROM d)::SMALLINT,

    CASE
        WHEN EXTRACT(ISODOW FROM d) IN (6, 7)
        THEN TRUE
        ELSE FALSE
    END

FROM generate_series(
    (
        SELECT MIN(pickup_date)
        FROM staging.yellow_taxi_trips
    ),
    (
        SELECT MAX(tpep_dropoff_datetime::DATE)
        FROM staging.yellow_taxi_trips
    ),
    INTERVAL '1 day'
) AS series(d);


-- ============================================================
-- 2. ZONE DIMENSION
-- ============================================================

CREATE TABLE warehouse.dim_zone (
    zone_key INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_id INTEGER UNIQUE,
    borough VARCHAR(50),
    zone VARCHAR(100),
    service_zone VARCHAR(50)
);


-- Unknown zone
INSERT INTO warehouse.dim_zone (
    zone_key,
    location_id,
    borough,
    zone,
    service_zone
)
VALUES (
    0,
    NULL,
    'Unknown',
    'Unknown',
    'Unknown'
);


-- Actual zones
INSERT INTO warehouse.dim_zone (
    location_id,
    borough,
    zone,
    service_zone
)
SELECT
    location_id,
    borough,
    zone,
    service_zone
FROM staging.taxi_zone_lookup
WHERE location_id IS NOT NULL;


-- ============================================================
-- 3. VENDOR DIMENSION
-- ============================================================

CREATE TABLE warehouse.dim_vendor (
    vendor_key INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vendor_id SMALLINT UNIQUE
);


-- Unknown vendor
INSERT INTO warehouse.dim_vendor (
    vendor_key,
    vendor_id
)
VALUES (
    0,
    NULL
);


-- Actual vendors
INSERT INTO warehouse.dim_vendor (
    vendor_id
)
SELECT DISTINCT
    vendor_id
FROM staging.yellow_taxi_trips
WHERE vendor_id IS NOT NULL;


-- ============================================================
-- 4. PAYMENT TYPE DIMENSION
-- ============================================================

CREATE TABLE warehouse.dim_payment_type (
    payment_type_key INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_type_code SMALLINT UNIQUE,
    payment_type_name VARCHAR(50)
);


-- Unknown
INSERT INTO warehouse.dim_payment_type (
    payment_type_key,
    payment_type_code,
    payment_type_name
)
VALUES (
    0,
    NULL,
    'Unknown'
);


-- Actual payment types
INSERT INTO warehouse.dim_payment_type (
    payment_type_code,
    payment_type_name
)
SELECT DISTINCT
    payment_type,

    CASE payment_type
        WHEN 0 THEN 'Flex Fare'
        WHEN 1 THEN 'Credit Card'
        WHEN 2 THEN 'Cash'
        WHEN 3 THEN 'No Charge'
        WHEN 4 THEN 'Dispute'
        ELSE 'Other'
    END

FROM staging.yellow_taxi_trips
WHERE payment_type IS NOT NULL;


-- ============================================================
-- 5. RATE CODE DIMENSION
-- ============================================================

CREATE TABLE warehouse.dim_rate_code (
    rate_code_key INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rate_code_id SMALLINT UNIQUE
);


-- Unknown
INSERT INTO warehouse.dim_rate_code (
    rate_code_key,
    rate_code_id
)
VALUES (
    0,
    NULL
);


-- Actual rate codes
INSERT INTO warehouse.dim_rate_code (
    rate_code_id
)
SELECT DISTINCT
    ratecode_id
FROM staging.yellow_taxi_trips
WHERE ratecode_id IS NOT NULL;


-- ============================================================
-- 6. FACT TABLE
-- ============================================================

CREATE TABLE warehouse.fact_trips (

    trip_key BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    -- Dimension keys
    pickup_date_key INTEGER NOT NULL,
    dropoff_date_key INTEGER NOT NULL,

    pickup_zone_key INTEGER NOT NULL,
    dropoff_zone_key INTEGER NOT NULL,

    vendor_key INTEGER NOT NULL,
    payment_type_key INTEGER NOT NULL,
    rate_code_key INTEGER NOT NULL,

    -- Trip timestamps
    pickup_datetime TIMESTAMP NOT NULL,
    dropoff_datetime TIMESTAMP NOT NULL,

    -- Trip measurements
    passenger_count NUMERIC(8,2),
    trip_distance NUMERIC(14,3),
    trip_duration_minutes NUMERIC(12,2),

    -- Financial measurements
    fare_amount NUMERIC(12,2),
    extra NUMERIC(12,2),
    mta_tax NUMERIC(12,2),
    tip_amount NUMERIC(12,2),
    tolls_amount NUMERIC(12,2),
    improvement_surcharge NUMERIC(12,2),
    total_amount NUMERIC(12,2),
    congestion_surcharge NUMERIC(12,2),
    airport_fee NUMERIC(12,2),
    cbd_congestion_fee NUMERIC(12,2),

    fare_per_mile NUMERIC(14,4),

    -- Quality flags
    negative_total_amount BOOLEAN,
    zero_distance BOOLEAN,
    zero_duration BOOLEAN,
    zero_passenger_count BOOLEAN,
    missing_passenger_count BOOLEAN,

    -- Derived anomaly flags
    is_financial_anomaly BOOLEAN,
    is_operational_anomaly BOOLEAN

);


-- ============================================================
-- 7. LOAD FACT TABLE
-- ============================================================

INSERT INTO warehouse.fact_trips (

    pickup_date_key,
    dropoff_date_key,

    pickup_zone_key,
    dropoff_zone_key,

    vendor_key,
    payment_type_key,
    rate_code_key,

    pickup_datetime,
    dropoff_datetime,

    passenger_count,
    trip_distance,
    trip_duration_minutes,

    fare_amount,
    extra,
    mta_tax,
    tip_amount,
    tolls_amount,
    improvement_surcharge,
    total_amount,
    congestion_surcharge,
    airport_fee,
    cbd_congestion_fee,

    fare_per_mile,

    negative_total_amount,
    zero_distance,
    zero_duration,
    zero_passenger_count,
    missing_passenger_count,

    is_financial_anomaly,
    is_operational_anomaly

)

SELECT

    -- Pickup date
    COALESCE(
        dd_pick.date_key,
        0
    ),

    -- Dropoff date
    COALESCE(
        dd_drop.date_key,
        0
    ),

    -- Pickup zone
    COALESCE(
        zp.zone_key,
        0
    ),

    -- Dropoff zone
    COALESCE(
        zd.zone_key,
        0
    ),

    -- Vendor
    COALESCE(
        v.vendor_key,
        0
    ),

    -- Payment
    COALESCE(
        p.payment_type_key,
        0
    ),

    -- Rate code
    COALESCE(
        r.rate_code_key,
        0
    ),

    -- Datetimes
    s.tpep_pickup_datetime,
    s.tpep_dropoff_datetime,

    -- Trip metrics
    s.passenger_count,
    s.trip_distance,
    s.trip_duration_minutes,

    -- Financial metrics
    s.fare_amount,
    s.extra,
    s.mta_tax,
    s.tip_amount,
    s.tolls_amount,
    s.improvement_surcharge,
    s.total_amount,
    s.congestion_surcharge,
    s.airport_fee,
    s.cbd_congestion_fee,

    s.fare_per_mile,

    -- Quality flags
    s.negative_total_amount,
    s.zero_distance,
    s.zero_duration,
    s.zero_passenger_count,
    s.missing_passenger_count,

    -- Financial anomaly
    s.negative_total_amount,

    -- Operational anomaly
    (
        s.zero_distance
        OR
        s.zero_duration
        OR
        s.zero_passenger_count
        OR
        s.missing_passenger_count
    )

FROM staging.yellow_taxi_trips s

LEFT JOIN warehouse.dim_date dd_pick
    ON dd_pick.full_date = s.pickup_date

LEFT JOIN warehouse.dim_date dd_drop
    ON dd_drop.full_date =
       s.tpep_dropoff_datetime::DATE

LEFT JOIN warehouse.dim_zone zp
    ON zp.location_id = s.pulocation_id

LEFT JOIN warehouse.dim_zone zd
    ON zd.location_id = s.dolocation_id

LEFT JOIN warehouse.dim_vendor v
    ON v.vendor_id = s.vendor_id

LEFT JOIN warehouse.dim_payment_type p
    ON p.payment_type_code = s.payment_type

LEFT JOIN warehouse.dim_rate_code r
    ON r.rate_code_id = s.ratecode_id

WHERE s.is_valid_record = TRUE;


-- ============================================================
-- 8. INDEXES
-- ============================================================

CREATE INDEX idx_fact_pickup_date
ON warehouse.fact_trips(pickup_date_key);

CREATE INDEX idx_fact_pickup_zone
ON warehouse.fact_trips(pickup_zone_key);

CREATE INDEX idx_fact_dropoff_zone
ON warehouse.fact_trips(dropoff_zone_key);

CREATE INDEX idx_fact_payment
ON warehouse.fact_trips(payment_type_key);

CREATE INDEX idx_fact_vendor
ON warehouse.fact_trips(vendor_key);

